# Generated by Django 5.2.4 on 2025-08-13 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('man', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managementstaff',
            name='is_hr',
            field=models.BooleanField(default=False, help_text="If worker can employ and layoff other workers (which don't have hr role) select the checkbox", verbose_name='Is HR'),
        ),
    ]
