# Generated by Django 5.2.4 on 2025-08-13 16:41

import dentman.storage
import dentman.utils
import django.core.validators
import pathlib
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('man', '0002_alter_managementstaff_is_hr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employment',
            name='contract_scan',
            field=models.FileField(storage=dentman.storage.CustomFileSystemStorage(base_url='/man/contract', location=pathlib.PurePosixPath('/app/storage/contr')), upload_to=dentman.utils.get_upload_path, validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='Contract scan file'),
        ),
    ]
