# Generated by Django 5.2.4 on 2025-08-13 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('man', '0003_alter_employment_contract_scan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employment',
            name='until_when',
            field=models.DateField(blank=True, help_text='Date until new employee works (select only when job is for limited time)', null=True, verbose_name='Until when'),
        ),
    ]
