# Generated by Django 5.2.4 on 2025-08-13 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('man', '0004_alter_employment_until_when'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employment',
            name='type_of_employment',
            field=models.CharField(choices=[('full_time', 'Full-time'), ('part_time', 'Part-time'), ('contract', 'Contract'), ('fixed_term', 'Fixed-term'), ('temporary', 'Temporary'), ('internship', 'Internship'), ('traineeship', 'Traineeship'), ('volunteer', 'Volunteer')], max_length=20, verbose_name='Type of employment'),
        ),
    ]
