# Generated by Django 5.2.4 on 2025-12-10 08:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('man', '0005_alter_employment_type_of_employment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='bonus_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Bonus amount'),
        ),
    ]
