# Generated by Django 5.2.9 on 2025-12-31 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('man', '0006_alter_bonus_bonus_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='dentiststaff',
            name='is_dentist_assistant',
            field=models.BooleanField(default=False, verbose_name='Is dentist assistant'),
        ),
        migrations.AlterField(
            model_name='dentiststaff',
            name='is_dentist',
            field=models.BooleanField(default=False, verbose_name='Is dentist'),
        ),
    ]
