cache-dir = "/ve/.cache"
experimental.new-installer = true
experimental.system-git-client = false
installer.parallel = true
virtualenvs.options.always-copy = false
virtualenvs.options.no-pip = false
virtualenvs.options.no-setuptools = false
virtualenvs.options.system-site-packages = false
virtualenvs.prefer-active-python = false
virtualenvs.prompt = "{project_name}"
virtualenvs.path = "/ve"
virtualenvs.in-project = false
virtualenvs.create = false