# Generated by Django 5.2.4 on 2025-07-19 20:51

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0003_discount_post_visitstatus_visit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text_html',
            field=tinymce.models.HTMLField(help_text="Blog's text written in HTML format", verbose_name='Text html'),
        ),
    ]
