# Generated by Django 5.2.4 on 2025-07-20 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0005_alter_post_main_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitstatus',
            name='is_accepted_by_patient',
        ),
    ]
