# Generated by Django 5.2.4 on 2025-07-20 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0006_remove_visitstatus_is_accepted_by_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitstatus',
            name='is_booked',
            field=models.BooleanField(default=False, verbose_name='Is visit booked'),
        ),
    ]
