# Generated by Django 5.2.4 on 2025-07-20 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0009_alter_discount_used_counter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='used_counter',
            field=models.IntegerField(default=0, verbose_name='Discount used counter'),
        ),
    ]
