# Generated by Django 5.2.4 on 2025-07-20 21:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0010_alter_discount_used_counter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='percent',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0, 'Value cannot be less than 0'), django.core.validators.MaxValueValidator(100, 'Value cannot be greater than 100')], verbose_name='Discount percent'),
        ),
    ]
