# Generated by Django 5.2.4 on 2025-07-20 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0011_alter_discount_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='promotion_code',
            field=models.CharField(blank=True, max_length=30, verbose_name='Promotion code'),
        ),
    ]
