# Generated by Django 5.2.4 on 2025-07-20 21:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0012_discount_promotion_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='limit_value',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0, 'Value cannot be less than 0')], verbose_name='Discount limit value'),
        ),
    ]
