# Generated by Django 5.2.4 on 2025-07-20 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0015_discount_why_invalid_summary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='is_actually_valid',
        ),
        migrations.AddField(
            model_name='discount',
            name='is_currently_valid',
            field=models.BooleanField(default=False, verbose_name='Is currently valid'),
        ),
    ]
