# Generated by Django 5.2.4 on 2025-07-20 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0016_remove_discount_is_actually_valid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='description',
            field=models.TextField(blank=True, verbose_name='Discount description'),
        ),
    ]
