# Generated by Django 5.2.4 on 2025-07-21 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0018_alter_visit_additional_info_alter_visit_ending_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='final_price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Final price of service including discounts', max_digits=10, verbose_name='Final price'),
        ),
    ]
