# Generated by Django 5.2.4 on 2025-07-21 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0019_visit_final_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='additional_info',
            field=models.TextField(blank=True, null=True, verbose_name='Additional information'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='ending_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Visit ending time'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='starting_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Visit starting time'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='visit_description',
            field=models.TextField(blank=True, null=True, verbose_name='Visit description'),
        ),
    ]
