# Generated by Django 5.2.4 on 2025-08-07 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0020_alter_visit_additional_info_alter_visit_ending_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is discount active'),
        ),
    ]
