# Generated by Django 5.2.4 on 2025-08-07 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0021_discount_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='discounts',
            field=models.ManyToManyField(blank=True, related_name='discounts', to='ops.discount', verbose_name='Discounts'),
        ),
    ]
