# Generated by Django 5.2.4 on 2025-08-07 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0022_alter_visit_discounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ops.service', verbose_name='Service'),
        ),
    ]
