# Generated by Django 5.2.4 on 2025-08-21 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0023_visit_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='promotion_code',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Promotion code'),
        ),
    ]
