from . import (
     env, ALLOWED_HOSTS, APPS_DIR, AUTH_PASSWORD_VALIDATORS,
    AUTH_USER_MODEL, DATABASES, DEBUG, DEFAULT_AUTO_FIELD, ENV, ENV_FILE,
    INSTALLED_APPS, LANGUAGE_CODE, LOGGING, MEDIA_ROOT, MEDIA_URL,
    MIDDLEWARE, ROOT_DIR, ROOT_URLCONF, SECRET_KEY, SECURE_PROXY_SSL_HEADER,
    STATIC_ROOT, STATIC_URL, STORAGE_ROOT, STORAGE_URL, TEMPLATES, TIME_ZONE, USE_I18N,
    USE_TZ, WSGI_APPLICATION, STATICFILES_DIRS,
)

DEBUG = True

INSTALLED_APPS = ["whitenoise.runserver_nostatic"] + INSTALLED_APPS 
MIDDLEWARE = ["whitenoise.middleware.WhiteNoiseMiddleware"] + MIDDLEWARE 