# Generated by Django 5.2.4 on 2025-07-13 12:18

import dentman.app.models
import dentman.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_user_additional_info_user_is_dev_user_is_patient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='additional_info',
            field=models.TextField(blank=True, null=True, verbose_name='Additional information'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_dev',
            field=models.BooleanField(default=False, verbose_name='Is developer'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_patient',
            field=models.BooleanField(default=True, verbose_name='Is patient'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_worker',
            field=models.BooleanField(default=False, verbose_name='Is worker'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, storage=dentman.storage.CustomFileSystemStorage(), upload_to=dentman.app.models.get_upload_path, verbose_name='Profile photo'),
        ),
    ]
