# Generated by Django 5.2.4 on 2025-07-13 12:42

import dentman.app.models
import dentman.storage
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_user_additional_info_alter_user_is_dev_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(storage=dentman.storage.CustomFileSystemStorage(), upload_to=dentman.app.models.get_upload_path, validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'png', 'mp4'])], verbose_name='File')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('additional_info', models.TextField(blank=True, null=True, verbose_name='Additional information')),
            ],
            options={
                'verbose_name': 'Attachment',
                'verbose_name_plural': 'Attachments',
            },
        ),
        migrations.CreateModel(
            name='AttachmentEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(verbose_name='Object ID')),
                ('attachment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.attachment', verbose_name='Attachment')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Content type')),
            ],
            options={
                'verbose_name': "Attachment's entity",
                'verbose_name_plural': "Attachments' entities",
            },
        ),
    ]
