# Generated by Django 5.2.4 on 2025-07-13 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_attachment_attachmententity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measurement_type', models.PositiveSmallIntegerField(choices=[(1, 'Length'), (2, 'Weight'), (3, 'Amount')], verbose_name='Measurement type')),
                ('measurement_name', models.CharField(max_length=100, verbose_name='Measurement name')),
                ('measurement_name_shortcut', models.CharField(max_length=10, verbose_name='Measurement name shortcut')),
            ],
            options={
                'verbose_name': 'Metric',
                'verbose_name_plural': 'Metrics',
            },
        ),
    ]
