# Generated by Django 5.2.4 on 2025-07-19 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_metrics'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_dentist',
            field=models.BooleanField(default=False, verbose_name='Is dentist'),
        ),
    ]
