# Generated by Django 5.2.4 on 2025-07-27 20:35

import dentman.storage
import dentman.utils
import django.core.validators
import uuid
from django.db import migrations, models

def generate_eid_for_existing_users(apps, schema_editor):
    User = apps.get_model('app', 'User')
    for user in User.objects.filter(eid__isnull=True):
        user.eid = uuid.uuid4()
        user.save(update_fields=["eid"])

class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_user_is_dentist'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='eid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(storage=dentman.storage.CustomFileSystemStorage(base_url='/user-profile/'), upload_to=dentman.utils.get_upload_path, validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'png', 'mp4'])], verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, storage=dentman.storage.CustomFileSystemStorage(base_url='/user-profile/'), upload_to=dentman.utils.get_upload_path, verbose_name='Profile photo'),
        ),
        migrations.RunPython(generate_eid_for_existing_users),
    ]
