# Generated by Django 5.2.4 on 2025-07-27 20:46

import dentman.app.models
import dentman.storage
import dentman.utils
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_user_eid_alter_attachment_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(storage=dentman.storage.CustomFileSystemStorage(base_url='/profile-photo/'), upload_to=dentman.utils.get_upload_path, validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'png', 'mp4'])], verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, storage=dentman.storage.CustomFileSystemStorage(base_url='/profile-photo/'), upload_to=dentman.app.models.get_profile_photo_upload_path, verbose_name='Profile photo'),
        ),
    ]
