# Generated by Django 5.2.4 on 2025-07-27 20:47

import dentman.storage
import dentman.utils
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_attachment_file_alter_user_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(storage=dentman.storage.CustomFileSystemStorage(), upload_to=dentman.utils.get_upload_path, validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'png', 'mp4'])], verbose_name='File'),
        ),
    ]
