# Generated by Django 5.2.4 on 2025-07-27 20:47

import dentman.app.models
import dentman.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_attachment_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, storage=dentman.storage.CustomFileSystemStorage(base_url='/app/profile-photo/'), upload_to=dentman.app.models.get_profile_photo_upload_path, verbose_name='Profile photo'),
        ),
    ]
