# Generated by Django 5.2.4 on 2025-08-26 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_attachment_created_at_attachment_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='Phone number'),
        ),
    ]
