# Generated by Django 5.2.4 on 2025-09-14 09:33

import dentman.storage
import dentman.utils
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(storage=dentman.storage.CustomFileSystemStorage(), upload_to=dentman.utils.get_upload_path_with_class, validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'png', 'mp4'])], verbose_name='File'),
        ),
    ]
