# Generated by Django 5.2.9 on 2025-12-31 20:03

from django.db import migrations, models

from dentman.utils import check_if_user_is_adult


def set_is_adult_flag(apps, schema_editor):
    User = apps.get_model("app", "User")

    for user in User.objects.all():
        if user.birth_date:
            user.is_adult = check_if_user_is_adult(user)
        else:
            user.is_adult = False
        user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_user_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_adult',
            field=models.BooleanField(default=False, verbose_name='Is adult'),
        ),
        migrations.RunPython(set_is_adult_flag)
    ]
