# Generated by Django 5.2.9 on 2025-12-31 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_user_is_adult'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_dentist',
        ),
        migrations.AddField(
            model_name='user',
            name='is_dentist_assistant',
            field=models.BooleanField(default=False, verbose_name='Is dentist assistant'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_dentist_staff',
            field=models.BooleanField(default=False, verbose_name='Is dentist staff'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_financial',
            field=models.BooleanField(default=False, verbose_name='Is financial'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_hr',
            field=models.BooleanField(default=False, verbose_name='Is HR'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_management_staff',
            field=models.BooleanField(default=False, verbose_name='Is management staff'),
        ),
    ]
