# Generated by Django 5.2.9 on 2025-12-31 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_remove_user_is_dentist_user_is_dentist_assistant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_dentist',
            field=models.BooleanField(default=False, verbose_name='Is dentist'),
        ),
    ]
